**Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [1]:
import numpy as np

In [6]:
n = 10
array_1 = np.arange(0, n)
array_2 = array_1[::-1]
print(array_2)

[9 8 7 6 5 4 3 2 1 0]


**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.


In [7]:
np.diag(array_2)

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [13]:
line = np.arange(array_2.shape[0])
print(sum(line))

45


**Задание 3**
Решите систему уравнений:


In [15]:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

In [16]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [17]:
b = np.array( [4, 12, -3] )

In [18]:
from numpy import linalg

In [19]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [20]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

**Задание 4** Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [29]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
)

In [30]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [47]:
list_cosines = []
for line in users_stats:
    cosines = np.dot(next_user_stats, line) / (np.linalg.norm(next_user_stats) * np.linalg.norm(line))
    #print(cosines)
    list_cosines.append(cosines)
    
print(list_cosines.index(max(list_cosines)))

7
